apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity: {}
      terminationGracePeriodSeconds: 0
      securityContext: {}
      containers:
        - image: nginx
          lifecycle: {}
          name: nginx
          resources:
            limits:
              cpu: 25m
              memory: 64Mi
          securityContext: {}
