apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: secret-sa-dependency
spec:
  target:
    apiVersion: v1
    kind: Secret
  customizations:
    dependencyInterpretation:
      luaScript: >
        function GetDependencies(desiredObj)
          saName = desiredObj.metadata.annotations["kubernetes.io/service-account.name"]
          dependencies = {}
          if saName ~= nil and saName ~= "" and saName ~= "default" then
            dependency = {}
            dependency.apiVersion = "v1"
            dependency.kind = "ServiceAccount"
            dependency.name = saName
            dependency.namespace = desiredObj.metadata.namespace
            dependencies[1] = dependency
            print("[DEBUG] saName: ", saName)
          end
          print("[DEBUG] end")
          return dependencies
        end
