apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: cpp
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Service
  placement:
    clusterAffinity:
      clusterNames:
        - member1
