apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: pp-delay-multi
spec:
  activationPreference: Lazy
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
    - apiVersion: v1
      kind: ConfigMap
      name: nginx-config
  placement:
    clusterAffinity:
      clusterNames:
        - member1
