apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: pp-delay-dep
spec:
  activationPreference: Lazy
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
