apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx
  type: NodePort
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
    - apiVersion: v1
      kind: Service
      name: nginx-service
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
---
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
  name: nginx
spec:
#  scaleMode: Distributed
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 3
    scaleUp:
      stabilizationWindowSeconds: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Value
          averageValue: 5Mi
          value: 4Mi
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 10
    - type: Resource
      resource:
        name: cpu
        target:
          type: Value
          averageValue: 5m
          value: 5m
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
