apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: karmada-system
---
apiVersion: v1
kind: Secret
metadata:
  name: spark-sa-secret
  namespace: karmada-system
  annotations:
    kubernetes.io/service-account.name: "spark"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: karmada-system
---
apiVersion: v1
kind: Service
metadata:
  name: spark-operator-webhook-svc
  namespace: karmada-system
spec:
  externalName: spark-operator-webhook-svc.karmada-system.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: driver-cpp
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      labelSelector:
        matchLabels:
          spark-app-name: spark-test
    - apiVersion: v1
      kind: Service
      labelSelector:
        matchLabels:
          sparkoperator.k8s.io/app-name: spark-test
    - apiVersion: v1
      kind: Service
      labelSelector:
        matchLabels:
          spark-app-name: spark-test
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: executor-cpp
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      labelSelector:
        matchLabels:
          spark-app-name: spark-pi
  placement:
    clusterAffinity:
      clusterNames:
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
