apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-test-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:v3.1.3"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - "harbor-secret"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar"
  sparkVersion: "3.1.1"
  #hadoopConfigMap: hadoop-conf
  sparkConf:
    #spark.eventLog.enabled: false
    #spark.master: "k8s://https://10.207.8.147:31000"
    spark.rss.storage.type: MEMORY_LOCALFILE
    spark.executor.extraJavaOptions: "-DlogTarget=Console -DbootstrapServers=127.0.0.1:9092"
    spark.driver.extraJavaOptions: "-DlogTarget=Console -DbootstrapServers=127.0.0.1:9092"
    spark.kubernetes.driver.master: "https://10.207.8.147:31000"
    spark.kubernetes.authenticate.submission.caCertPath: "/etc/spark/certs/ca.crt"
    spark.kubernetes.authenticate.submission.clientCertPath: "/etc/spark/certs/client.crt"
    spark.kubernetes.authenticate.submission.clientKeyPath: "/etc/spark/certs/client.key"
  restartPolicy:
    type: Never
  volumes:
    - name: spark-certs-volume
      secret:
        secretName: spark-certs
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    #    kubernetesMaster: https://10.207.8.147:31000
    #    env:
    #      - name: KUBERNETES_SERVICE_HOST
    #        value: 10.207.8.147
    #      - name: KUBERNETES_SERVICE_PORT
    #        value: "31000"
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: spark-certs-volume
        mountPath: "/etc/spark/certs"
        subPath: ""
    serviceAccount: big-data-service
  executor:
    #    env:
    #      - name: KUBERNETES_SERVICE_HOST
    #        value: 10.207.8.147
    #      - name: KUBERNETES_SERVICE_PORT
    #        value: "31000"
    coreRequest: "1m"
    coreLimit: "50m"
    instances: 20
    memory: "500m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: spark-certs-volume
        mountPath: "/etc/spark/certs"
        subPath: ""
