apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-test
  template:
    metadata:
      labels:
        app: demo-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: demo-test
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
