kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  apiServerAddress: 7.250.138.110
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 5443
      hostPort: 5443
      protocol: TCP
      listenAddress: 127.0.0.1