apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: karmada-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: karmada-system
    name: argo
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
  namespace: karmada-system
  annotations:
    kubernetes.io/service-account.name: argo
type: kubernetes.io/service-account-token
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lVQ1dFbzBwYy9jd1R6RmtsUXpKR2UzWVRMMEtvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF3d0hhMkZ5YldGa1lUQWVGdzB5TXpFd01UUXhNelF4TVRsYUZ3MHpNekV3TVRFeApNelF4TVRsYU1CSXhFREFPQmdOVkJBTU1CMnRoY20xaFpHRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRREc1NDZRZ0h0a2phM3RTd2ltbjFJUjBHdUlXNFR4QXlOeUt4NC9iWWpETk9sMy9lcUUKbThNQmVpNVo4RGVPYXZZazdOSFNlK2ZvRDVGb3JYemhSZXFlcUltcW5nQWcrMmZoT3MzR2dUZTgyMDFQdGljWQp5NVJJY0F6L2FHaW54aWFhY0pwc1E5MDErVkhTcGRqL2cwekpzUW9XL3I4SExjSUh5djEwN2daOTBnZGFyWVZWCmtvWE5OVVhVOWFjcEVDblgrRDA5L1NUdmNNNXV1NkRoUiszUWhDd01sUnhha1N4TVlsVE96cC91Q3lXcUxObmoKbFlOSGw1ZjZpanU2RVV3WDkrc2hOM2NnV1dhaXBGRVVpMGNUWlFUdEFFZ28za09GMTdiMG1uWFhxMTZxZCtKUQpWQmxsQXBGNEIwbVNaMGNkUk4zN21sbGE4MUt6Q2xoaSs1YVRBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlNHCmZQanF4ZGp3MDBLcE9VRHk3NnVFeksxb3lEQWZCZ05WSFNNRUdEQVdnQlNHZlBqcXhkancwMEtwT1VEeTc2dUUKeksxb3lEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU9rd3hCZlhrVAo0NnRld2tydEZDWGc2VFFJODBYR0JrNWVMNUVoZ3pOOEhpYVVqQUxiM3RIY2g2RVdZa2lXVVBnbEpNdWZOZzhBCkR6Mm1FWE5NYTgvOW5idEl0M2k3WmtoTXh6OHI2aFRQTDV4VGZoZmFjbENkV0JrMUNXcDN2emtrRmJ1MndLOFIKNGswSFFmanJBcStXVVVFY0VTd3cwR1BUTmhWRGk5WEkzeUU5cFlMZDVySTNHN3FKK0R5cWtxZkdYN1k4NC8wagpQdkR0L2tlOS9sUytGT2srZ09pNExwS3drczZlOUl1QitnRzBWRForZ2xibDI5TlNZOXY4UjR2MFQ4WWkyK3RmClUraVZtYzBQYmtkZHM0N0pTT2JDUGlEUFliRTlFS0xSdmlCSXJKL0dzNDNzSTlkQmplajB6SXR1dUU5eGRUVi8KbC9HRjJPNk5TalNBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  namespace: a2FybWFkYS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpMXFPRlpaVkhwZlMxcHNhM0pTWVVkbVNIcFZTMFpFUmxnME0wVmFUMnd3VmsxMlIxVk9VRnBZZUZFaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyWVhKdFlXUmhMWE41YzNSbGJTSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWamNtVjBMbTVoYldVaU9pSmhjbWR2TFhObFkzSmxkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG01aGJXVWlPaUpoY21kdklpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU9EWmhaRFV6TURjdE4yWXpaQzAwWXpJM0xXRm1aalF0TnpJeVpqRm1Oak5sTWpaaklpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXRoY20xaFpHRXRjM2x6ZEdWdE9tRnlaMjhpZlEuWnFDbkMtbGhzMnlYUTNqQlZVak5tcS15bUxLdkQwN3hJRUNFODNlOXdkdlkwV3dOMWw0TTZOR1p0c1ROdi1kZGk4RHF5cktPLWlPcEN3ZTd6WGhaTW9CMXdxWENsR1FaZ1JibmtPbGVvUTkzRTM4eHctUUhOeUlHWm81UWhZc1F1NExtTklVWnlhOEZBSnk1NFVKbDdHQXp5MldXZm5ORFRIblYyUmNiUkJUSWFkaHVaWFhSZHR5NWQyR0toaEdmbUtKWDEtclBtU3BLSFFVM0MwcmJNbVFoVDJsUDc3Mkp2RTdQSlpneVp5aUp3SFBoYlB2YV96aC1NZ29HX1c1N2dyREtHa1AxTUxsMHBqZk5uQW9VQUZSOWlUZURPNVZ0eks2Y3M0RHl5cHloQTlyblJrdEJ0al9wNEViQnZPMXRQTmFNWUhaUVp4aDY0ZWcydmxxcnF3


