
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.200.78.158","10.200.78.159"],"port":80,"protocol":"HTTP","serviceName":"gw-pre:hwork-backend-gateway-config","ingressName":"gw-pre:hwork-backend-gateway-config-d5876e21","hostname":"5138.hwork-backend-gateway-config.gw-pre.huangdao-test-n.haier.net","path":"/","allNodes":false},{"addresses":["10.200.78.158","10.200.78.159"],"port":80,"protocol":"HTTP","serviceName":"gw-pre:hwork-backend-gateway-config","ingressName":"gw-pre:hwork-backend-gateway-config-d5876e21","hostname":"5138.hwork-backend-gateway-config.gw-pre.859679566930.openplat.net","path":"/","allNodes":false}]'
    k8s.haier.net/description: ""
    k8s.haier.net/display-name: python-code-executor
    k8s.haier.net/updated-timestamp: "2024-01-31T05:58:55Z"
  labels:
    app: python-code-executor
    app.kubernetes.io/name: python-code-executor
    app.kubernetes.io/version: v0
    k8s.haier.net/app-type: ""
    k8s.haier.net/dslVersion: v1alpha
    k8s.haier.net/tenant: hdscoms
    velero.io/backup-name: velero-qd-huangdao-test-20231129133059
    velero.io/restore-name: velero-qd-huangdao-test-20231129133059-20231129142127
  name: python-code-executor
  namespace: gzc-multi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-code-executor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-code-executor
        app.kubernetes.io/name: python-code-executor
        app.kubernetes.io/version: v0
        k8s.haier.net/tenant: hdscoms
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: c0
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 30
