apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    k8s.haier.net/display-name: python-code-executor
    k8s.haier.net/updated-timestamp: "2024-02-02T06:45:54Z"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"k8s.haier.net/display-name":"python-code-executor"},"labels":{"app":"python-code-executor","app.kubernetes.io/name":"python-code-executor","app.kubernetes.io/version":"v0","k8s.haier.net/dslVersion":"v1alpha","k8s.haier.net/tenant":"hdscoms"},"name":"python-code-executor","namespace":"gzc-multi"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"python-code-executor"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"python-code-executor","app.kubernetes.io/name":"python-code-executor","app.kubernetes.io/version":"v0","k8s.haier.net/tenant":"hdscoms"}},"spec":{"containers":[{"image":"reg-qd-huangdao.haier.net/hdscoms_gitlab/python-code-executor:v0.0.3-b-master-9b5030adaaf36579b2330fad440367338cff3c39","imagePullPolicy":"Always","name":"c0","resources":{"limits":{"cpu":"100m","memory":"64Mi"},"requests":{"cpu":"100m","memory":"64Mi"}},"securityContext":{"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","securityContext":{"runAsNonRoot":false},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2024-01-31T03:40:55Z"
  generation: 27
  labels:
    app: python-code-executor
    app.kubernetes.io/name: python-code-executor
    app.kubernetes.io/uid: 9ab2ed286e237743
    app.kubernetes.io/version: v0
    k8s.haier.net/dslVersion: v1alpha
    k8s.haier.net/tenant: hdscoms
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.haier.net/updated-timestamp: {}
    manager: applacation
    operation: Update
    time: "2024-01-31T03:44:13Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2024-02-02T03:36:00Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:k8s.haier.net/display-name: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/uid: {}
          f:app.kubernetes.io/version: {}
          f:k8s.haier.net/dslVersion: {}
          f:k8s.haier.net/tenant: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:app.kubernetes.io/name: {}
              f:app.kubernetes.io/version: {}
              f:k8s.haier.net/tenant: {}
          f:spec:
            f:containers:
              k:{"name":"c0"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"a"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"b"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"c"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:privileged: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext:
              .: {}
              f:runAsNonRoot: {}
            f:terminationGracePeriodSeconds: {}
    manager: karmada-controller-manager
    operation: Update
    time: "2024-02-02T06:27:16Z"
  name: python-code-executor
  namespace: gzc-multi
  resourceVersion: "2223533117"
  uid: 93d7c872-f10d-4e3c-8337-5fa6bdb22730
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-code-executor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-code-executor
        app.kubernetes.io/name: python-code-executor
        app.kubernetes.io/version: v0
        k8s.haier.net/tenant: hdscoms
    spec:
      containers:
      - env:
        - name: a
          value: a
        - name: b
          value: b1
        - name: c
          value: c
        image: nginx
        imagePullPolicy: Always
        name: c0
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-31T03:41:00Z"
    lastUpdateTime: "2024-01-31T03:41:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-31T03:40:55Z"
    lastUpdateTime: "2024-02-02T03:36:00Z"
    message: ReplicaSet "python-code-executor-6c6d866ff7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
