# docker build --tag ubuntu:2.0 .
# docker tag ubuntu:2.0 alpine:3.20.2
FROM ubuntu:18.04

# install common utils
RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN apt update && apt install -y --fix-missing vim curl make dnsutils iputils-ping wget net-tools apt-utils  \
    apt-transport-https ca-certificates software-properties-common gnupg gnupg2 lsb-release bridge-utils git

# install zsh
RUN apt install -y zsh
RUN chsh -s $(which zsh)
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN sed -i "s/(git)/(git zsh-autosuggestions zsh-syntax-highlighting)/g" ~/.zshrc
RUN sed -i "s/robbyrussell/af-magic/g" ~/.zshrc
RUN sed -i "/source \$ZSH\/oh-my-zsh.sh/i\source \/etc\/profile" ~/.zshrc

# install tzdata
RUN DEBIAN_FRONTEND=noninteractive apt install -y tzdata

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/bin/zsh"]
